* emt

This dynamic module serves as an interface to invoke macOS's built-in NLP tokenizer, specifically the =NLTokenizer=.

** Build

This module is written in Swift, and requires macOS 10.15 or later.

#+begin_src bash
  # For release
  swift build -c release

  # For debug
  swift build
#+end_src

If you enconter the error =No such module "PackageDescription"=, you should install Xcode and run the following command:

#+begin_src bash
  sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
#+end_src

** Usage

The module provides three functions:

- =emt--do-split-helper=

    This function takes a string intended for tokenization, and returns a list of ConsCell, which contains the word and its bounds.
  
- =emt--do-split-without-bounds=

    This function takes a string intended for tokenization, and returns a list of words.

    While this function does not calculate the bounds of the words, it is faster than =emt--do-split-helper=.

- =emt--word-at-point-or-forward=

    This functions takes a string and a position, and returns the word at the position. If the position is at the bound of two words, it returns the word at the right side of that position.

** Acknowledgement

This module uses [[https://github.com/SavchenkoValeriy/emacs-swift-module.git][emacs-swift-module]], which provides an interface for writing Emacs dynamic modules in Swift.
