* emt

This dynamic module serves as an interface to invoke macOS's built-in NLP tokenizer, specifically the =NLTokenizer=.

** Build

This module is written in Swift, and requires macOS 10.15 or later.

#+begin_src bash
  # For release
  swift build -c release

  # For debug
  swift build
#+end_src

If you enconter the folloing error:

#+begin_quote
No such module "PackageDescription"
#+end_quote

run the following command and try again:

#+begin_src bash
  sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
#+end_src

** Usage

The module provides two functions:

- =emt--do-split-helper=

    This function takes a string and return an array of bounds. A bound is a cons with the starting position and the ending position of a word.

- =emt--word-at-point-or-forward=

    This functions takes a string and a position, and returns the bound of the word at the position. If the position is at bound of two words, it returns the word at the right side of that position. This function does not tokenize the whole string, so it is faster in some cases.

** Acknowledgement

This module uses [[https://github.com/SavchenkoValeriy/emacs-swift-module.git][emacs-swift-module]], which provides an interface for writing Emacs dynamic modules in Swift.
